"""Physics-informed SCADA simulator with labelled fault injection.

Why simulate instead of shipping a CSV?
---------------------------------------
Two reasons, both about defensibility:

1. **Ground truth.** Published SCADA datasets (EDP, CARE, Kelmarsh, ...) either
   lack per-sample fault labels or carry licence terms that prevent
   redistribution. Without labels, anomaly-detection metrics are unverifiable.
2. **Reproducibility.** A seeded simulator means every number in this
   repository can be regenerated byte-for-byte by a reviewer.

The model is not a toy noise generator. Wind is generated as a Rayleigh
turbulent process, air density follows the ideal gas law, and power is produced
by an actual power-coefficient surface ``Cp(lambda, beta)`` with a region-2
(optimal tip-speed-ratio) / region-3 (rated-power pitch) controller. Pitch
angle in region 3 is *solved* for by bisection rather than asserted, so the
generated signals remain mutually consistent under the laws of physics. Faults
perturb the physical state (or the sensor), never the label.

Physics references
------------------
* Cp surface: Heier, S. *Grid Integration of Wind Energy Conversion Systems*,
  eq. for ``Cp(lambda, beta)`` (the widely used ``c1..c6`` parameterisation).
* Wake deficits: Jensen, N.O. (1983) wake model, as used in farm-layout tools.
* Density: ideal gas law with ``R_specific = 287.05 J/kg/K``.

Fault taxonomy (maps onto the fabric's fault-probability vector)
----------------------------------------------------------------
===================== ============================ ==================
kind                  physical signature           affected plane
===================== ============================ ==================
``gearbox_thermal``   oil/nacelle temperature      thermal
``bearing_wear``      main-bearing vibration       vibration / mechanical
``pitch_misalignment`` power deficit + 1P ripple    rotor / aerodynamic
``yaw_error``         cos^3 power loss + yaw duty   rotor / control
``converter_fault``   current ripple, power dips    electrical
``sensor_freeze``     stuck channel                 instrumentation
``sensor_drift``      undeclared slow bias          instrumentation
===================== ============================ ==================
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from wt_pm_lstm.config import DataConfig
from wt_pm_lstm.schema import (
    CHANNELS,
    QUALITY_MISSING,
    QUALITY_OK,
    QUALITY_OUT_OF_RANGE,
    QUALITY_STUCK,
    QUALITY_SUSPECT,
    TurbineTimeline,
    canonical_channels,
    get_channel,
)

# --------------------------------------------------------------------------
# Physical constants and machine model
# --------------------------------------------------------------------------
R_SPECIFIC_AIR = 287.05  # J/(kg K)
STD_PRESSURE_PA = 101325.0
CP_COEFFS = (0.5176, 116.0, 0.4, 5.0, 21.0, 0.0068)  # c1..c6, Heier
OPTIMAL_TSR = 8.1  # lambda at beta = 0 for this Cp surface
GEARBOX_TAU_MIN = 110.0
NACELLE_TAU_MIN = 45.0
GEN_VOLTAGE_V = 690.0
GRID_NOMINAL_HZ = 50.0

FAULT_KINDS = (
    "gearbox_thermal",
    "bearing_wear",
    "pitch_misalignment",
    "yaw_error",
    "converter_fault",
    "sensor_freeze",
    "sensor_drift",
)

#: Measurement-noise model, ``(relative, absolute)`` in physical units. Real
#: SCADA instrumentation noise is heteroscedastic: a 3 MW power reading is
#: noisier in absolute terms than a 50 kW one, while a thermocouple is noisy in
#: absolute terms regardless of level. The absolute floor is set near each
#: channel's quantisation step, since a converter cannot resolve below its LSB.
NOISE_SPEC: Dict[str, Tuple[float, float]] = {
    "wind_speed_ms": (0.040, 0.05),
    "ambient_temp_c": (0.002, 0.15),
    "rotor_speed_rpm": (0.010, 0.02),
    "pitch_angle_deg": (0.010, 0.05),
    "yaw_error_deg": (0.020, 0.10),
    "power_kw": (0.012, 5.0),
    "main_shaft_torque_knm": (0.015, 3.0),
    "generator_current_a": (0.015, 5.0),
    "grid_frequency_hz": (0.0, 0.005),
    "nacelle_temp_c": (0.002, 0.10),
    "gearbox_oil_temp_c": (0.002, 0.10),
    "bearing_vib_rms_mm_s": (0.060, 0.02),
}

#: Channels measured as magnitudes: their support excludes negative values, so
#: noise is applied and clipped accordingly rather than producing physically
#: impossible negative RMS/current readings.
NON_NEGATIVE_CHANNELS = (
    "rotor_speed_rpm",
    "yaw_error_deg",
    "bearing_vib_rms_mm_s",
    "generator_current_a",
)

#: Channels each fault kind is allowed to freeze/drift, chosen so the injected
#: signature is realistic (e.g. a pitch sensor is not stuck to gearbox oil).
SENSOR_FAULT_TARGETS = {
    "sensor_freeze": ("gearbox_oil_temp_c", "bearing_vib_rms_mm_s", "nacelle_temp_c", "power_kw"),
    "sensor_drift": ("gearbox_oil_temp_c", "bearing_vib_rms_mm_s", "nacelle_temp_c", "generator_current_a"),
}


# --------------------------------------------------------------------------
# Statics
# --------------------------------------------------------------------------
def _norm_cdf(x: np.ndarray) -> np.ndarray:
    """Vectorised standard normal CDF (tanh approximation, |err| < 1e-3).

    A rational/tanh approximation is used instead of ``scipy.special.erf`` so
    the reference engine stays NumPy-only. The approximation error is far below
    the sensor noise floor and therefore irrelevant to the fault signatures.
    """
    return 0.5 * (1.0 + np.tanh(0.7988 * x * (1.0 + 0.04417 * x * x)))


def _ar1(rng: np.random.Generator, n: int, phi: float, sigma: float = 1.0) -> np.ndarray:
    """Stationary AR(1) process with unit-variance innovations scaled by sigma."""
    eps = rng.standard_normal(n) * sigma * np.sqrt(1.0 - phi**2)
    out = np.empty(n, dtype=np.float64)
    acc = 0.0
    for i in range(n):
        acc = phi * acc + eps[i]
        out[i] = acc
    return out


def _ramp(n_steps: int, onset: int, duration: int, ramp_fraction: float = 0.35) -> np.ndarray:
    """Fault severity profile in ``[0, 1]`` with a realistic onset ramp.

    Faults are not step functions: a bearing does not fail between two SCADA
    samples. The ramp fraction controls how much of the fault window is spent
    degrading, which directly sets how *detectable* the fault is and is the
    honest way to study detection latency.
    """
    s = np.zeros(n_steps, dtype=np.float64)
    stop = min(n_steps, onset + duration)
    if stop <= onset:
        return s
    seg = np.arange(stop - onset, dtype=np.float64)
    ramp_len = max(1.0, ramp_fraction * duration)
    s[onset:stop] = np.clip(seg / ramp_len, 0.0, 1.0)
    return s


def cp_of_lambda_beta(lam: np.ndarray, beta: np.ndarray) -> np.ndarray:
    """Power coefficient surface ``Cp(lambda, beta)`` (Heier parameterisation).

    ``lam`` is the tip-speed ratio, ``beta`` the collective pitch in degrees.
    Values are clipped to the physical range ``[0, Cp_max]``: the analytic form
    is only valid inside its fitted domain and can return small negative values
    for absurd ``(lam, beta)`` combinations.
    """
    c1, c2, c3, c4, c5, c6 = CP_COEFFS
    lam_safe = np.maximum(lam, 1e-3)
    beta_safe = np.maximum(beta, 0.0)
    denom = 1.0 / (lam_safe + 0.08 * beta_safe) - 0.035 / (beta_safe**3 + 1.0)
    lam_i = 1.0 / np.maximum(denom, 1e-6)
    cp = c1 * (c2 / lam_i - c3 * beta_safe - c4) * np.exp(-c5 / lam_i) + c6 * lam_safe
    return np.clip(cp, 0.0, 0.593)  # Betz limit


def air_density(temp_c: np.ndarray) -> np.ndarray:
    """Air density from the ideal gas law at standard pressure."""
    return STD_PRESSURE_PA / (R_SPECIFIC_AIR * (temp_c + 273.15))


def _solve_pitch_for_power(lam: np.ndarray, cp_required: np.ndarray) -> np.ndarray:
    """Invert ``Cp(lambda, beta)`` for ``beta`` by bisection (region 3).

    Vectorised bisection over the whole record. This is what makes the
    simulated pitch angle physically consistent instead of arbitrary: given the
    wind, rotor speed and power setpoint, the pitch that achieves rated power is
    *determined*, not chosen.
    """
    lo = np.zeros_like(lam)
    hi = np.full_like(lam, 35.0)
    for _ in range(48):
        mid = 0.5 * (lo + hi)
        cp_mid = cp_of_lambda_beta(lam, mid)
        too_much = cp_mid > cp_required
        lo = np.where(too_much, mid, lo)
        hi = np.where(too_much, hi, mid)
    return 0.5 * (lo + hi)


# --------------------------------------------------------------------------
# Fault schedule
# --------------------------------------------------------------------------
@dataclass(frozen=True)
class FaultSpec:
    """One scheduled fault event."""

    kind: str
    onset_step: int
    duration_steps: int
    magnitude: float = 1.0
    channel: str = ""
    turbine_index: int = 0

    @property
    def stop_step(self) -> int:
        return self.onset_step + self.duration_steps

    def to_dict(self) -> Dict[str, object]:
        return {
            "kind": self.kind,
            "onset_step": self.onset_step,
            "duration_steps": self.duration_steps,
            "magnitude": self.magnitude,
            "channel": self.channel,
            "turbine_index": self.turbine_index,
        }


def default_fault_schedule(
    n_steps: int,
    first_fault_step: int,
    kinds: Sequence[str] = FAULT_KINDS,
    seed: int = 0,
    turbine_index: int = 0,
    min_gap_steps: int = 24,
) -> List[FaultSpec]:
    """Schedule one event per fault kind after the healthy prefix.

    Events are separated by at least ``min_gap_steps`` so that detection
    latency and per-fault recall are attributable to a single cause. The
    healthy prefix (used for fitting) and the calibration band are never
    contaminated by construction.
    """
    rng = np.random.default_rng(seed)
    specs: List[FaultSpec] = []
    cursor = first_fault_step
    for kind in kinds:
        duration = int(rng.integers(48, 180))  # 8 h to 30 h at 10-min sampling
        stop = cursor + duration
        if stop > n_steps - 6:
            break
        channel = ""
        if kind in SENSOR_FAULT_TARGETS:
            channel = str(rng.choice(SENSOR_FAULT_TARGETS[kind]))
        specs.append(
            FaultSpec(
                kind=kind,
                onset_step=int(cursor),
                duration_steps=duration,
                magnitude=float(rng.uniform(0.7, 1.3)),
                channel=channel,
                turbine_index=turbine_index,
            )
        )
        cursor = stop + int(rng.integers(min_gap_steps, 4 * min_gap_steps))
    return specs


# --------------------------------------------------------------------------
# Core simulation
# --------------------------------------------------------------------------
def _ar1_loop(phi: float, innovations: np.ndarray, init: float = 0.0) -> np.ndarray:
    out = np.empty_like(innovations)
    acc = init
    for i in range(innovations.size):
        acc = phi * acc + innovations[i]
        out[i] = acc
    return out


def simulate_timeline(
    cfg: DataConfig,
    seed: Optional[int] = None,
    fault_specs: Optional[Sequence[FaultSpec]] = None,
    wind_override: Optional[np.ndarray] = None,
    wind_direction_deg: Optional[np.ndarray] = None,
    turbine_id: Optional[str] = None,
) -> TurbineTimeline:
    """Generate one turbine's labelled SCADA timeline.

    Parameters
    ----------
    cfg
        Data-generation settings.
    seed
        Overrides ``cfg.seed`` (used to give each farm turbine a distinct
        turbulence realisation while keeping the wind field correlated).
    fault_specs
        Faults to inject. ``[]`` means "healthy-only record", which is what the
        training and calibration splits require.
    wind_override
        Externally supplied hub-height wind speed (used by :func:`simulate_fleet`
        to impose wake deficits).
    """
    seed = cfg.seed if seed is None else seed
    rng = np.random.default_rng(seed)

    n = int(cfg.n_days * 24 * 60 / cfg.sample_minutes)
    dt_min = float(cfg.sample_minutes)
    dt_s = dt_min * 60.0
    t = np.arange(n) * dt_s
    ts = np.asarray(1700000000 + t, dtype=np.int64)

    # ---- environment ------------------------------------------------------
    day_of_year = 60.0 + (np.arange(n) * dt_min / (60.0 * 24.0))  # start late Feb
    if wind_override is None:
        # Rayleigh-distributed wind from a latent Gaussian, with diurnal and
        # synoptic-scale structure. sigma calibred so E[v] = cfg.mean_wind_ms.
        latent = _ar1_loop(0.985, rng.standard_normal(n) * 0.13)
        latent += 0.12 * np.sin(2.0 * np.pi * np.arange(n) / (9 * 24 * 60 / dt_min))
        u = np.clip(_norm_cdf(latent), 1e-6, 1 - 1e-6)
        sigma_v = cfg.mean_wind_ms / np.sqrt(np.pi / 2.0)
        wind = sigma_v * np.sqrt(-2.0 * np.log(1.0 - u))
        wind = np.clip(wind, 0.0, 34.0)
    else:
        wind = np.asarray(wind_override, dtype=np.float64).copy()
        if wind.shape != (n,):
            raise ValueError(f"wind_override must have shape ({n},), got {wind.shape}")

    temp = (
        cfg.mean_ambient_c
        + 7.0 * np.sin(2.0 * np.pi * (day_of_year - 105.0) / 365.0)
        + 3.2 * np.sin(2.0 * np.pi * (np.arange(n) * dt_min / 60.0 - 15.0) / 24.0)
        + _ar1_loop(0.97, rng.standard_normal(n) * 0.25)
    )

    if wind_direction_deg is None:
        wind_dir = 240.0 + _ar1_loop(0.995, rng.standard_normal(n) * 0.6)
    else:
        wind_dir = np.asarray(wind_direction_deg, dtype=np.float64)

    grid_freq = GRID_NOMINAL_HZ + _ar1_loop(0.9, rng.standard_normal(n) * 0.004)

    rho = air_density(temp)
    area = np.pi * cfg.rotor_radius_m**2
    omega_rated = cfg.rated_rotor_rpm * 2.0 * np.pi / 60.0  # rad/s
    omega_min = 0.52  # rad/s, ~5 rpm minimum operating speed

    # ---- fault severity profiles -----------------------------------------
    severity: Dict[str, np.ndarray] = {k: np.zeros(n) for k in FAULT_KINDS}
    frozen_channel: Dict[str, str] = {}
    drift_channel: Dict[str, str] = {}
    active_kinds: List[str] = []
    for spec in fault_specs or []:
        s = _ramp(n, spec.onset_step, spec.duration_steps) * spec.magnitude
        if spec.kind not in severity:
            raise ValueError(f"unknown fault kind {spec.kind!r}")
        severity[spec.kind] = np.maximum(severity[spec.kind], s)
        if spec.kind == "sensor_freeze" and spec.channel:
            frozen_channel[spec.channel] = spec.channel
        if spec.kind == "sensor_drift" and spec.channel:
            drift_channel[spec.channel] = spec.channel
        active_kinds.append(spec.kind)

    eff = np.full(n, cfg.drivetrain_efficiency)
    # Drivetrain efficiency degrades slightly under thermal and wear faults.
    eff -= 0.02 * severity["gearbox_thermal"] + 0.015 * severity["bearing_wear"]

    # ---- aerodynamic conversion ------------------------------------------
    # Region 2: track optimal tip-speed ratio at zero pitch.
    omega = OPTIMAL_TSR * wind / cfg.rotor_radius_m
    omega = np.clip(omega, omega_min, omega_rated)
    lam = omega * cfg.rotor_radius_m / np.maximum(wind, 1e-3)

    yaw = 2.5 + _ar1_loop(0.96, rng.standard_normal(n) * 0.35)
    yaw = np.abs(yaw) + 12.0 * severity["yaw_error"]  # extra misalignment
    yaw = np.clip(yaw, 0.0, 45.0)
    # Yaw misalignment costs power with a cos^3 law.
    yaw_factor = np.cos(np.deg2rad(yaw)) ** 3

    # Blade pitch misalignment (one blade out of track) mainly shows up as
    # asymmetric loading — 1P torque ripple and vibration — rather than as a
    # large mean power loss, because the collective cos^3 loss is small. The
    # linear power coefficient below is an engineering approximation (~1.2 % per
    # degree of collective-equivalent offset).
    pitch_offset = 4.0 * severity["pitch_misalignment"]
    pitch_factor = np.clip(1.0 - 0.012 * pitch_offset, 0.5, 1.0)

    pitch = np.zeros(n)
    power = np.zeros(n)
    torque = np.zeros(n)

    operating = (wind >= cfg.cut_in_wind_ms) & (wind <= cfg.cut_out_wind_ms)
    idle = ~operating

    # All power quantities below are in kW: 0.5*rho*A*v^3 is in watts, so the
    # aerodynamic expression carries an explicit /1000.
    def aero_kw(cp: np.ndarray, v: np.ndarray) -> np.ndarray:
        return 0.5 * rho * area * cp * v**3 * yaw_factor * pitch_factor / 1000.0

    # Region 2 candidate power.
    cp_r2 = cp_of_lambda_beta(lam, np.zeros(n))
    p_elec_r2 = eff * aero_kw(cp_r2, wind)

    # Region 3: hold rated speed and solve for the pitch that yields rated power.
    lam_r3 = omega_rated * cfg.rotor_radius_m / np.maximum(wind, 1e-3)
    cp_required = cfg.rated_power_kw / np.maximum(eff * aero_kw(np.ones(n), wind), 1e-9)
    pitch_r3 = _solve_pitch_for_power(lam_r3, cp_required)
    cp_r3 = cp_of_lambda_beta(lam_r3, pitch_r3)
    p_elec_r3 = eff * aero_kw(cp_r3, wind)

    region3 = operating & (p_elec_r2 > cfg.rated_power_kw)
    region2 = operating & ~region3

    power[region2] = p_elec_r2[region2]
    power[region3] = p_elec_r3[region3]
    omega[region3] = omega_rated
    pitch[region3] = pitch_r3[region3]

    # Idle / parked: blades feathered, auxiliaries draw a small negative power.
    power[idle] = -18.0 - 6.0 * rng.random(int(idle.sum()))
    omega[idle] = np.where(wind[idle] < 0.5, 0.0, omega_min * 0.35)
    pitch[idle] = 88.0 + 1.5 * rng.standard_normal(int(idle.sum()))

    # Converter fault: power dips, current ripple and torque oscillation.
    conv = severity["converter_fault"]
    if conv.any():
        dip = 1.0 - 0.18 * conv * (0.5 + 0.5 * np.sin(
            2.0 * np.pi * np.arange(n) * dt_min / 90.0
        ))
        power = np.where(operating, power * dip, power)

    # Main (low-speed) shaft torque: P / omega, with power in kW, omega in
    # rad/s yields kNm directly. Parked machines carry no torque.
    torque = np.where(omega > 0.1, np.maximum(power, 0.0) / np.maximum(omega, 1e-2), 0.0)
    # Pitch misalignment ripples the main-shaft torque at 1P.
    p1p = np.sin(2.0 * np.pi * np.arange(n) * dt_min * (omega * 60.0 / (2.0 * np.pi)) / 60.0)
    torque = np.where(torque > 0, torque * (1.0 + 0.02 * p1p * pitch_offset), torque)

    # ---- electrical ------------------------------------------------------
    load_fraction = np.clip(power / cfg.rated_power_kw, 0.0, 1.2)
    pf = 0.75 + 0.20 * np.clip(load_fraction, 0.0, 1.0)
    current = np.where(
        power > 0.0,
        np.abs(power) * 1000.0 / (np.sqrt(3.0) * GEN_VOLTAGE_V * pf),
        0.0,
    )
    # Converter fault: the switching ripple that a healthy converter filters
    # out reappears as measurement noise (10-minute SCADA aggregates it into a
    # variance increase, not into a resolvable waveform), together with an
    # occasional commutation dip. Variance inflation is what the residual heads
    # can actually see, so it is modelled explicitly rather than hidden.
    if conv.any():
        # A real converter protects itself by derating: the sustained 15 %
        # power limit is what a 10-minute SCADA record actually shows, alongside
        # the variance inflation below.
        power = np.where(operating, power * (1.0 - 0.15 * conv), power)
        current = np.where(operating, current * (1.0 - 0.15 * conv), current)
        ripple = 1.0 + 0.12 * conv * np.sin(2.0 * np.pi * np.arange(n) * dt_min / 50.0)
        current = np.where(operating, current * ripple, current)
        current = np.where(
            operating,
            current + conv * rng.standard_normal(n) * 0.10 * np.maximum(current, 1.0),
            current,
        )
        power = np.where(
            operating, power + conv * rng.standard_normal(n) * 0.06 * np.abs(power), power
        )
        dips = (rng.random(n) < 0.02 * conv)
        power = np.where(dips & operating, power * 0.75, power)

    # ---- thermal dynamics ------------------------------------------------
    # First-order lags towards load-dependent targets; the time constants are
    # the physically meaningful part (oil heats and cools much slower than the
    # nacelle air volume).
    nacelle_target = temp + 24.0 * np.clip(load_fraction, 0.0, 1.0) + 3.0 * (omega / omega_rated)
    oil_target = (
        temp
        + 34.0 * np.clip(load_fraction, 0.0, 1.0)
        + 4.0 * (omega / omega_rated)
        + 26.0 * severity["gearbox_thermal"]
        + 4.0 * severity["bearing_wear"]
    )
    a_nac = np.exp(-dt_min / NACELLE_TAU_MIN)
    a_oil = np.exp(-dt_min / GEARBOX_TAU_MIN)
    nacelle = np.empty(n)
    oil = np.empty(n)
    acc_n, acc_o = temp[0], temp[0]
    for i in range(n):
        acc_n = a_nac * acc_n + (1 - a_nac) * nacelle_target[i]
        acc_o = a_oil * acc_o + (1 - a_oil) * oil_target[i]
        nacelle[i] = acc_n
        oil[i] = acc_o

    # ---- vibration -------------------------------------------------------
    turbulence = np.abs(_ar1_loop(0.7, rng.standard_normal(n) * 0.25))
    vib = (
        0.45
        + 0.95 * (omega / omega_rated)
        + 0.35 * turbulence
        + 0.5 * (wind / cfg.rated_wind_ms) * (omega / omega_rated)
    )
    # Bearing wear raises broadband vibration amplitude roughly quadratically
    # once it is established, which is why early-stage wear is hard to detect.
    vib += (0.7 + 5.5 * severity["bearing_wear"] ** 2) * severity["bearing_wear"]
    # 1P/3P content from pitch imbalance: one blade out of track loads the shaft
    # once per revolution, which appears as vibration and torque ripple rather
    # than as a mean power deficit.
    vib += 0.45 * pitch_offset

    # ---- assemble --------------------------------------------------------
    columns = {
        "wind_speed_ms": wind,
        "ambient_temp_c": temp,
        "rotor_speed_rpm": omega * 60.0 / (2.0 * np.pi),
        "pitch_angle_deg": pitch,
        "yaw_error_deg": yaw,
        "power_kw": power,
        "main_shaft_torque_knm": torque,
        "generator_current_a": current,
        "grid_frequency_hz": grid_freq,
        "nacelle_temp_c": nacelle,
        "gearbox_oil_temp_c": oil,
        "bearing_vib_rms_mm_s": vib,
    }

    names = canonical_channels()
    values = np.column_stack([columns[name] for name in names])

    # The *physical* state must respect the contract envelope before any
    # measurement artefact is applied: physics does not emit negative rotor
    # speed. Out-of-range values in the delivered record therefore always have
    # an instrumentation explanation, which is exactly the situation the
    # detector faces in the field.
    for j, name in enumerate(names):
        spec = get_channel(name)
        values[:, j] = np.clip(values[:, j], spec.plausible_min, spec.plausible_max)

    quality = np.full(values.shape, QUALITY_OK, dtype=np.uint8)

    # Sensor noise + quantisation (what a real DAQ actually delivers).
    for j, name in enumerate(names):
        rel, abs_floor = NOISE_SPEC.get(name, (0.01, 0.0))
        sigma = cfg.sensor_noise * (rel * np.abs(values[:, j]) + abs_floor)
        values[:, j] += rng.standard_normal(n) * sigma
        if name in NON_NEGATIVE_CHANNELS:
            values[:, j] = np.maximum(values[:, j], 0.0)
        q = cfg.quantisation.get(name, 0.0)
        if q > 0:
            values[:, j] = np.round(values[:, j] / q) * q
        if name in NON_NEGATIVE_CHANNELS:
            values[:, j] = np.maximum(values[:, j], 0.0)

    # Dropouts and spikes. Spike magnitude is scaled by the channel's *own*
    # robust spread (MAD) rather than by its physical envelope, because a
    # glitch is defined relative to normal signal excursion: a 3 Hz jump is a
    # wild event for grid frequency but unremarkable for gearbox oil.
    drops = rng.random((n, len(names))) < cfg.dropout_rate
    values[drops] = np.nan
    quality[drops] = QUALITY_MISSING
    spikes = rng.random((n, len(names))) < cfg.spike_rate
    if spikes.any():
        rows, cols = np.where(spikes)
        robust_scale = np.array(
            [1.4826 * np.median(np.abs(values[:, j] - np.median(values[:, j]))) for j in range(len(names))]
        )
        robust_scale = np.maximum(robust_scale, 1e-6)
        magnitude = rng.uniform(4.0, 10.0, size=rows.size) * robust_scale[cols]
        values[rows, cols] += np.sign(rng.standard_normal(rows.size)) * magnitude
        quality[rows, cols] = QUALITY_SUSPECT

    # Stuck sensor: hold the last good value for the fault window. This is a
    # *sensor* fault, not a machine fault, and the contract must be able to say
    # so rather than blaming the gearbox.
    for channel in frozen_channel:
        j = names.index(channel)
        spec = next(s for s in (fault_specs or []) if s.kind == "sensor_freeze" and s.channel == channel)
        win = slice(spec.onset_step, min(n, spec.stop_step))
        flat = values[spec.onset_step, j]
        values[win, j] = flat
        quality[win, j] = QUALITY_STUCK

    # Drifting sensor: undeclared slow bias — the quality flag stays OK on
    # purpose, because in the field nobody annotates a slow sensor drift.
    for channel in drift_channel:
        j = names.index(channel)
        spec = next(s for s in (fault_specs or []) if s.kind == "sensor_drift" and s.channel == channel)
        span = get_channel(channel).plausible_max - get_channel(channel).plausible_min
        values[:, j] = values[:, j] + 0.06 * span * severity["sensor_drift"]

    # Out-of-range values are flagged, not deleted.
    mask = ~np.isnan(values)
    for j, name in enumerate(names):
        spec = get_channel(name)
        bad = mask[:, j] & ((values[:, j] < spec.plausible_min) | (values[:, j] > spec.plausible_max))
        quality[bad, j] = QUALITY_OUT_OF_RANGE
    values = np.nan_to_num(values, nan=0.0)

    fault_label = np.zeros(n, dtype=bool)
    fault_kind_per_step: List[str] = [""] * n
    for spec in fault_specs or []:
        stop = min(n, spec.stop_step)
        fault_label[spec.onset_step:stop] = True
        for i in range(spec.onset_step, stop):
            fault_kind_per_step[i] = spec.kind

    meta: Dict[str, object] = {
        "sampling_seconds": int(dt_s),
        "rated_power_kw": cfg.rated_power_kw,
        "rotor_radius_m": cfg.rotor_radius_m,
        "rated_rotor_rpm": cfg.rated_rotor_rpm,
        "optimal_tsr": OPTIMAL_TSR,
        "simulator_seed": int(seed),
        "fault_schedule": [s.to_dict() for s in (fault_specs or [])],
        "fault_kind_per_step": fault_kind_per_step,
        "wind_direction_deg": [round(float(x), 3) for x in wind_dir] if not turbine_id else None,
        "controller": "region2-tsr-tracking|region3-bisection-pitch",
        "physics": "heier-cp|ideal-gas-density|jensen-wake-available",
    }
    return TurbineTimeline(
        turbine_id=turbine_id or cfg.turbine_id,
        site_id=cfg.site_id,
        channel_names=names,
        values=values,
        timestamps=ts,
        mask=mask,
        quality=quality,
        fault_label=fault_label,
        fault_type=tuple(active_kinds),
        meta=meta,
    )


# --------------------------------------------------------------------------
# Fleet generation (hand-off to the wind-farm graph layer, model 08)
# --------------------------------------------------------------------------
def wake_deficit(
    positions: Sequence[Tuple[float, float]],
    target: int,
    wind_direction_deg: np.ndarray,
    rotor_radius_m: float,
    k_wake: float = 0.075,
    thrust_coeff: float = 0.8,
) -> np.ndarray:
    """Jensen-model velocity deficit on turbine ``target``, time series.

    Meteorological convention: ``wind_direction_deg`` is the direction the wind
    blows *from*, so the flow vector points the opposite way. For every other
    turbine the along-flow distance ``s`` and lateral offset ``lat`` are
    recomputed each timestep, because the wind direction is itself a time
    series — this is what couples the farm together and why wind direction is a
    required input to the graph layer (model 08).

    The deficit uses the standard Jensen form ``d = (1 - sqrt(1 - Ct)) *
    (R / (R + k s))^2`` with linear superposition of multiple wakes, and a
    smooth lateral overlap factor ``max(0, 1 - (lat / 2R)^2)`` that approximates
    the fraction of the rotor disc inside the wake cone.
    """
    n = wind_direction_deg.size
    xi, yi = positions[target]
    # Flow direction (towards) in farm coordinates: +x = east, +y = north.
    toward = np.deg2rad(wind_direction_deg) + np.pi
    fx, fy = np.sin(toward), np.cos(toward)

    deficit = np.zeros(n)
    root = 1.0 - np.sqrt(1.0 - thrust_coeff)
    for j, (xj, yj) in enumerate(positions):
        if j == target:
            continue
        dx, dy = xj - xi, yj - yi
        # s > 0 means turbine j is upstream of the target.
        s = -(dx * fx + dy * fy)
        lat = np.abs(-dx * fy + dy * fx)
        r_wake = rotor_radius_m + k_wake * np.maximum(s, 1.0)
        overlap = np.clip(1.0 - (lat / (2.0 * rotor_radius_m)) ** 2, 0.0, 1.0)
        contribution = root * (rotor_radius_m / r_wake) ** 2 * overlap
        deficit += np.where(s > 0.0, contribution, 0.0)
    return np.clip(deficit, 0.0, 0.6)


def simulate_fleet(
    cfg: DataConfig,
    n_turbines: int = 6,
    seed: Optional[int] = None,
    faults_per_turbine: bool = True,
) -> List[TurbineTimeline]:
    """Simulate a small wind farm with Jensen wake-coupled turbines.

    Turbines are laid out in a 3x2 grid and each machine sees the deficits of
    every machine upstream of it as the wind direction turns. This is the input
    the graph layer (model 08) needs in order to model wake and cascade
    relationships, and it is the reason a per-turbine detector that ignores
    farm context will systematically attribute wake effects to machine faults.
    """
    seed = cfg.seed if seed is None else seed
    rng = np.random.default_rng(seed)
    n = int(cfg.n_days * 24 * 60 / cfg.sample_minutes)

    # Layout: 3 columns crosswind (3D apart) by 2 rows downwind (7D apart),
    # D = 2R. Row spacing sits in the 5-8D band used by real farm layouts.
    D = 2.0 * cfg.rotor_radius_m
    positions = []
    for row in range(int(np.ceil(n_turbines / 3))):
        for col in range(min(3, n_turbines - 3 * row)):
            positions.append((col * 3.0 * D, row * 7.0 * D))

    # One shared wind field + per-turbine turbulence.
    base = simulate_timeline(cfg, seed=seed + 1, fault_specs=[]).channel("wind_speed_ms")
    wind_dir = 270.0 + _ar1_loop(0.997, rng.standard_normal(n) * 1.2)
    k_wake = 0.075  # Jensen wake decay constant (onshore)

    timelines: List[TurbineTimeline] = []
    for idx in range(n_turbines):
        x, y = positions[idx]
        deficit = wake_deficit(positions, idx, wind_dir, cfg.rotor_radius_m, k_wake)
        v_eff = base * (1.0 - deficit)
        v_eff = np.clip(v_eff + _ar1_loop(0.9, rng.standard_normal(n) * 0.08), 0.0, 34.0)

        specs: Sequence[FaultSpec] = []
        if faults_per_turbine:
            first = int(n * (cfg.healthy_fraction + cfg.calibration_fraction))
            specs = default_fault_schedule(
                n_steps=n,
                first_fault_step=first + idx * 5,
                kinds=cfg.fault_kinds,
                seed=seed + 100 + idx,
                turbine_index=idx,
            )
        timelines.append(
            simulate_timeline(
                cfg,
                seed=seed + 1000 + idx,
                fault_specs=specs,
                wind_override=v_eff,
                wind_direction_deg=wind_dir,
                turbine_id=f"{cfg.site_id}-WT{idx + 1:02d}",
            )
        )
        timelines[-1].meta["layout_xy_m"] = [float(x), float(y)]
        timelines[-1].meta["wake_deficit_mean"] = float(np.mean(deficit))
        timelines[-1].meta["wake_deficit_max"] = float(np.max(deficit))

    # The shared wind direction belongs to the site, not a single turbine.
    for tl in timelines:
        tl.meta.pop("wind_direction_deg", None)
    for tl in timelines:
        tl.meta["site_wind_direction_deg"] = [round(float(v), 3) for v in wind_dir]
    return timelines


__all__ = [
    "FaultSpec",
    "wake_deficit",
    "FAULT_KINDS",
    "cp_of_lambda_beta",
    "air_density",
    "default_fault_schedule",
    "simulate_timeline",
    "simulate_fleet",
]
